### ISSUE TITLE
Slack invite link not working

### ISSUE THREAD

**Issue by nabuskey** [cdevents/cdevents.dev#40]
The Slack invitation link is using the channel URL instead of the invitation URL. 

https://github.com/cdevents/cdevents.dev/blob/76d1098666172bd3d849946e34fbea0887aed1e5/content/en/community/_index.html#L63

When you click on it and you have not joined the CDF slack, there's no way to sign up because it's email domain restricted.

![image](https://github.com/cdevents/cdevents.dev/assets/21176944/179aa4c0-5433-4e5c-a977-91b6c83d9022)

I think it should be `https://join.slack.com/t/cdeliveryfdn/shared_invite/zt-nwc0jjd0-G65oEpv5ynFfPD5oOX5Ogg` per https://cd.foundation/community/.

**Comment by afrittoli** [comment]
Oh, thanks for reporting this, I will get the link fixed.
In the meanwhile, you can get the slack link from https://cd.foundation/, there's a slack link on the top right of the page
